### ISSUE TITLE
Trim logs' prefix

### ISSUE THREAD

**Issue by mdouchement** [mdouchement/composer#7]
In the following line, all the data before `:` should be trimmed.

```
D, [2016-11-07T17:23:10.549991 #1] DEBUG -- : The message !
```

It could be implemented with a regexp:
```yml
services:
  my_app:
    command: go run *.go
    log_trim_pattern: '.* : (?P<message>.*)'
```
